### ISSUE TITLE
SNPs per Dataset Vs SNPs per Samples

### ISSUE THREAD

**Issue by aardes** [elixirhub/human-data-beacon#1]
Hi Jordi,

I have a question regarding the data, In your database structure you have a table to store the datasets information, and then another table for the list of variants per dataset.
What I am suggesting is that to go one level lower and add the samples as well.
So it will be something like  this:
Tbl_Samples to keep the samples information
Tbl_Dataset to keeo the dataset information
Tbl_Dataset_Samples to define which  samples are belong to which datasets
Tbl_Sample_Variants to store the variants per samples

by this way later If we decided to show more information to the registered users we can show the frequency of the variant as well as more sample specific information.

**Comment by sdelatorrep** [comment]
Hi @aardes , you're totally right. A more complex database is required. In this v0.4 it has already been enhanced but, as more features are added, more and more information will be needed.

**Comment by sdelatorrep** [comment]
Hi @aardes . If you check the current schema, it's exactly what you suggested here (long time ago :) ). 
I'm closing this issue now.
