### ISSUE TITLE
Cannot handle datasets with call_cnt > 2147483647

### ISSUE THREAD

**Issue by bhosking** [elixirhub/human-data-beacon#22]
The dataset call count is typically near 2 * variant_count * sample_count, and as such can sometimes be over the value that can be stored in an integer.
I think the postgres data type should be changed to bigint, and the java type change to Long.

**Comment by sdelatorrep** [comment]
Hi! You're totally right. I found this issue in the EGA Beacon where we have millions of variants (and uses basically the same base code) but totally forgot to fix it in this repo. Thanks for spotting this!
