### ISSUE TITLE
Implement support for 0.4 specification

### ISSUE THREAD

**Issue by juhtornr** [elixirhub/human-data-beacon#4]

**Comment by sdelatorrep** [comment]
Update the Elixir reference implementation so 0.4 version of the spec is supported. This includes support for structural variants, range queries and Consent Codes (we are not including ADA-M in this first release).

**Comment by sdelatorrep** [comment]
Changes applied in new branch [v0.4](https://github.com/ga4gh-beacon/beacon-elixir/tree/v0.4). 
They include upgrading the Spring Boot version and implementing support for v0.4.

**Comment by sdelatorrep** [comment]
Some issues detected in the VCF parser provided with the reference implementation:
* VCF field `AC` should be used for the `variantCount` field in `DatasetAlleleResponse`.
* VCF field `AN` should be used for the `callCount` field in `DatasetAlleleResponse`.
* VCF field `AF` should be used for the `frequency`field in `DatasetAlleleResponse`.

From the VCF specification:

> AN : total number of alleles in called genotypes
> AC : allele count in genotypes, for each ALT allele, in the same order as listed
> AF : allele frequency for each ALT allele in the same order as listed: use this when estimated from primary data, not called genotypes
